# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Lab1
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packages"
  EB_APPLICATION_NAME : "MyCICDLab1"
  EB_ENVIRONMENT_NAME : "MyCICDLab1-env"
  DEPLOY_PACKAGE_NAME : "Lab1_app_${{ github.sha }}.zip"
  AWS_REGION_NAME : "us-west-2"

on:
  push:
    branches: -master

jobs:
  test_build_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: run a 1-line script
      run: echo Hello, world! Im work!
      
      
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone repo
    - uses: actions/checkout@v1
    
    - name : Create ZIP deploy package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* 
      #створення зіп пакету проекта з уникненням файлів гіта
      
   
   
